# Generated by Django 2.2.2 on 2019-06-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='data',
        ),
        migrations.AddField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(default=0),
        ),
    ]
